# docker run -d -p 5000:5000 -v .:/composeapp --link redis:redis --name dengqinghua/composeapp python app.py
web:
  image: dengqinghua/composeapp
  command: python app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/composeapp
redis:
  image: redis
